### ISSUE TITLE
Specify work-group size for single_task

### ISSUE THREAD

**Issue by keryell** [triSYCL/triSYCL#120]
In the current implementation, `single_task` just spawns a kernel with a work-group of size `(1,1,1)`.

But the device compiler does not add a decoration for it.
So we should have a `__attribute__((reqd_work_group_size(1, 1, 1)))` on the generated kernel.
Perhaps it is enough to put it in the triSYCL runtime in `instantiate_kernel()` and having a specialized version of it for this case?

**Comment by yu810226** [comment]
This enhancement is done in https://github.com/yu810226/llvm/tree/linya/sycl/reqd-workgroup-size-fpga
And please use clang in branch https://github.com/yu810226/clang/tree/linya/sycl/device-no-loop-idiom

**Comment by keryell** [comment]
This feature has been merged in.
