### ISSUE TITLE
Build fails at "vector_operators" ...

### ISSUE THREAD

**Issue by justxi** [triSYCL/triSYCL#127]
Hello,

the build fails with the following error message:

[ 97%] Building CXX object tests/vector/CMakeFiles/vector_operators.dir/operators.cpp.o
In file included from /usr/lib/gcc/i686-pc-linux-gnu/7.2.0/include/g++-v7/cassert:44:0,
                 from /usr/include/boost/test/impl/execution_monitor.ipp:47,
                 from /usr/include/boost/test/minimal.hpp:53,
                 from /home/wilfried/Projects/2017-11-triSYCL/triSYCL/tests/vector/operators.cpp:8:
/home/wilfried/Projects/2017-11-triSYCL/triSYCL/tests/vector/operators.cpp: In lambda function:
/home/wilfried/Projects/2017-11-triSYCL/triSYCL/tests/vector/operators.cpp:17:3: error: statement-expressions are not allowed outside functions nor in template-argument lists
   assert(v.size() == verif.size());
   ^
make[2]: *** [tests/vector/CMakeFiles/vector_operators.dir/build.make:63: tests/vector/CMakeFiles/vector_operators.dir/operators.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:4795: tests/vector/CMakeFiles/vector_operators.dir/all] Error 2
make: *** [Makefile:95: all] Error 2

I cloned the repository and run the following commands:
> mkdir build
> cd build
> export CC=/usr/bin/gcc-7.2.0
> export CXX=/usr/bin/g++-7.2.0
> cmake ../
> make

I also tried it with the current stable g++ 5.4.0-r3 on Gentoo Linux, same error. 
Boost 1.63.

Do I miss anything?

Thanks for any hints.

regards

  W. Holzke

**Comment by keryell** [comment]
I guess you are using a too old compiler.

Nowadays we use mostly Clang 5 and GCC 7, otherwise some tests are failing.

**Comment by justxi** [comment]
I tried it with Clang-4.0.1 and it builds up to 100%. When I build it with gcc-7.2.0 I get the same error as mentioned above. Line 17 "assert(v.size() == verif.size());" fails to build, commenting it out, it compiles.

Are you using any patches for gcc?

**Comment by justxi** [comment]
I tried this:
-------------------------------------------
#include <iostream>
#include <valarray>
#include <assert.h>

auto equal = [] (auto const &v, auto const &verif) {
  /* Do not use directly v == verif because we want to verify the
     (implicit) constructor itself */
  assert(v.size() == verif.size());
  auto p = std::begin(verif);
  for (auto e : v)
    if (e != *p++)
      return false;

  return true;
};


int main() {


	std::valarray<float> va1 { 1, 2, 3, 4};
	std::valarray<float> va2 { 1, 2, 3, 4, 5};

	std::cout << equal(va1,va2) << std::endl;
}
-------------------------------------------
... and compiled it with "g++-7.2.0 -std=c++14 main.cpp"... and ist compiles and works as expected.

**Comment by keryell** [comment]
So do you mean that this test fails with default CMake configuration and GCC 7.2 ?
In this test, `equal` is a generic lambda, requiring C++14.
That is strange because in `cmake/FindTriSYCL.cmake` there is
```
    add_compile_options("-std=c++1z") # Use latest available C++ standard

```
that sounds stronger than `-std=c++14` anyway...

For the tests using `tests/Makefile` we use only `-std=c++1y`, but this is still C++14.
I need to update the required version to be coherent between the 2 ways of testing...

**Comment by MathiasMagnus** [comment]
I'll also give the build a spin. Plus, the c++ language version enforcement needs some tweaking. I should update the scripts to use the compiler agnostic CXX_STANDARD property...

_(Plus how long have I wanted to update the find scripts of both triSYCL and ComputeCpp to make it detect both and have a unified interface...)_

**Comment by justxi** [comment]
To keryell: yes, I agree that it should work with std=c++1z, but it fails... 

And yes ... I used the original build files after cloning the repo.

If you have any ideas let me know... I will test it.

**Comment by keryell** [comment]
Any feedback with your newer environment and newer triSYCL?

**Comment by justxi** [comment]
I checked out the current version of triSYCL (git clone https://github.com/triSYCL/triSYCL/) and build it with gcc-7.3.0 (mkdir build; cd build; cmake ..; make). Now it finishes the build up to 100%.

**Comment by keryell** [comment]
Great!
So I close this issue.
