### ISSUE TITLE
Make clearer the use of include/CL/sycl/detail/unimplemented.hpp

### ISSUE THREAD

**Issue by keryell** [triSYCL/triSYCL#138]
For now a lot of unimplemented features just call
`cl::sycl::detail::unimplemented()` from
`include/CL/sycl/detail/unimplemented.hpp`

It would be nice to have a deeper API, for example taking an argument
describing what is not implemented, and also a macro to call this
function and displaying in which function, file, line... it is called.

**Comment by airlied** [comment]
just on this topic @keryell what is your feeling on padding out the API with unimplemented stubs?
I've got a bunch of patches in my dev tree that adds unimplemented stubs to get CTS to at least compile, just wondering if I should group them together and send them out.

**Comment by keryell** [comment]
Yes, that seems a good way to have the code compiling in the short term.

**Comment by keryell** [comment]
https://github.com/triSYCL/triSYCL/pull/187 seems to fit the job.
Thanks @airlied
