### ISSUE TITLE
non-CL type definitions incorrect for 1 element

### ISSUE THREAD

**Issue by airlied** [triSYCL/triSYCL#158]
When I changed code to start returning cl::sycl::cl_uint values, tests stopped building when OPENCL is disabled, as we end up defining cl_uint to be a vec<unsigned int, 1> which is incorrect.

However fixing the definition of this breaks tests/vector/cl_types.cpp as the equal function expects the vectors.

**Comment by airlied** [comment]
[First attempt at a fix is here](https://github.com/triSYCL/triSYCL/pull/153/commits/7c4d751204156a4f12bd3803ba94069c0db38179)

**Comment by airlied** [comment]
Put this patch on its own in #160

**Comment by keryell** [comment]
I have the feeling I somehow solved this in https://github.com/triSYCL/triSYCL/pull/291/commits/086d30ede6b163f3408a508f4da4a034f0541de8
