### ISSUE TITLE
SYCL compiler interoperability scalar datatypes

### ISSUE THREAD

**Issue by keryell** [triSYCL/triSYCL#16]
Implement types such as ``cl::sycl::cl_int`` so we can have example portable when the host and OpenCL devices do not have the same encoding of basic types.

See example https://github.com/keryell/triSYCL/blob/8b63e62e61d44365f641a9c7ba87a15ec0e5201f/tests/kernel/opencl_kernel_vector_add_args_42.cpp

**Comment by a-doumoulakis** [comment]
Solved with #49
