### ISSUE TITLE
Remove buffer::set_final_data(shared_ptr_class<T> finalData)

### ISSUE THREAD

**Issue by keryell** [triSYCL/triSYCL#18]
This is redundant with the `weak_ptr` version.

**Comment by JoanThibault** [comment]
I thought that when using set_final_data(shared_ptr) the user shares the ownership of the pointer with the buffer. But with set_final_data(weak_ptr) the buffer does not own the pointer.
One could argue that: if the buffer is the only one to own the pointer there is no point to trigger a write-back.
That could be true ... except that the shared pointer has a deleter, futrhermore as this deleter can trigger a copy (or some kind of operatation which uses these data to produce a result that is written outside of the memory managed by the shared_pointer), we can't move the destruction of the shared_pointer.

**Comment by keryell** [comment]
This is something to push inside the Khronos SYCL committee if you are motivated. :-)
But I think it stretch a little bit the raison d'être of the std::shared_ptr...

**Comment by keryell** [comment]
Close by https://github.com/triSYCL/triSYCL/pull/208
