### ISSUE TITLE
Build of examples fails to link with Boost::filesystem and OpenMP

### ISSUE THREAD

**Issue by Ghostkeeper** [triSYCL/triSYCL#201]
I'm trying to build triSYCL using CMake and running into the following errors:

    C:\Persoonlijk\Projecten\Libraries\triSYCL\build>mingw32-make install
    [  0%] Linking CXX executable 2014-04-21-HPC-GPU_Meetup_slide_21.exe
    CMakeFiles\2014-04-21-HPC-GPU_Meetup_slide_21.dir/objects.a(slide_21.cpp.obj):slide_21.cpp:(.text+0x277): undefined reference to `boost::filesystem::path::make_preferred()'
    CMakeFiles\2014-04-21-HPC-GPU_Meetup_slide_21.dir/objects.a(slide_21.cpp.obj):slide_21.cpp:(.text+0x1a07): undefined reference to `GOMP_parallel'
    CMakeFiles\2014-04-21-HPC-GPU_Meetup_slide_21.dir/objects.a(slide_21.cpp.obj):slide_21.cpp:(.text+0x27dd): undefined reference to `omp_get_num_threads'
    CMakeFiles\2014-04-21-HPC-GPU_Meetup_slide_21.dir/objects.a(slide_21.cpp.obj):slide_21.cpp:(.text+0x27e5): undefined reference to `omp_get_thread_num'
    CMakeFiles\2014-04-21-HPC-GPU_Meetup_slide_21.dir/objects.a(slide_21.cpp.obj):slide_21.cpp:(.text$_ZN5boost10filesystem11path_traits7convertEPKcS3_RNSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEE[_ZN5boost10filesystem11path_traits7convertEPKcS3_RNSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEE]+0x15): undefined reference to `boost::filesystem::path::codecvt()'
    CMakeFiles\2014-04-21-HPC-GPU_Meetup_slide_21.dir/objects.a(slide_21.cpp.obj):slide_21.cpp:(.text$_ZN5boost10filesystem11path_traits7convertEPKcS3_RNSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEE[_ZN5boost10filesystem11path_traits7convertEPKcS3_RNSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEE]+0x32): undefined reference to `boost::filesystem::path_traits::convert(char const*, char const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&, std::codecvt<wchar_t, char, int> const&)'
    CMakeFiles\2014-04-21-HPC-GPU_Meetup_slide_21.dir/objects.a(slide_21.cpp.obj):slide_21.cpp:(.text$_ZN5boost10filesystem11path_traits7convertEPKwS3_RNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN5boost10filesystem11path_traits7convertEPKwS3_RNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x15): undefined reference to `boost::filesystem::path::codecvt()'
    CMakeFiles\2014-04-21-HPC-GPU_Meetup_slide_21.dir/objects.a(slide_21.cpp.obj):slide_21.cpp:(.text$_ZN5boost10filesystem11path_traits7convertEPKwS3_RNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN5boost10filesystem11path_traits7convertEPKwS3_RNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x32): undefined reference to `boost::filesystem::path_traits::convert(wchar_t const*, wchar_tconst*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::codecvt<wchar_t, char, int> const&)'
    CMakeFiles\2014-04-21-HPC-GPU_Meetup_slide_21.dir/objects.a(slide_21.cpp.obj):slide_21.cpp:(.text$_ZNK2cl4sycl7nd_itemILi3EE7barrierENS0_6access11fence_spaceE[_ZNK2cl4sycl7nd_itemILi3EE7barrierENS0_6access11fence_spaceE]+0x12): undefined reference to `GOMP_barrier'
    collect2.exe: error: ld returned 1 exit status
    mingw32-make[2]: *** [tests\2014-04-21-HPC-GPU_Meetup\CMakeFiles\2014-04-21-HPC-GPU_Meetup_slide_21.dir\build.make:89: tests/2014-04-21-HPC-GPU_Meetup/2014-04-21-HPC-GPU_Meetup_slide_21.exe] Error 1
    mingw32-make[1]: *** [CMakeFiles\Makefile2:1092: tests/2014-04-21-HPC-GPU_Meetup/CMakeFiles/2014-04-21-HPC-GPU_Meetup_slide_21.dir/all] Error 2
    mingw32-make: *** [Makefile:162: all] Error 2

These are my relevant system specs:
* Windows 8.1
* CMake 3.12.3
* MinGW-w64 version 8.1.0 v6 (posix threads, SEH exceptions)
* Boost 1.68, compiled manually using the same compiler toolchain.
* My OpenCL is provided by NVidia. I'm unsure on how to get the exact specs of the implementation but it supports up to OpenCL 1.2, not OpenCL 2 yet.

I compiled using the CMake options TRISYCL_OPENCL and TRISYCL_OPENMP enabled. CMake isn't complaining and neither is the compiler. This error occurs while linking.

I didn't figure out why your examples are using Boost::filesystem, but CMake does search for it (and find it properly in my case).

Adding the following line to tests/CMakeLists.txt, after the `add_sycl_to_target` line, fixed the problem for me, and causes it to link properly:

    target_link_libraries(${TARGET_NAME} PUBLIC Boost::filesystem gomp)

However this is not how you're supposed to link OpenMP. That normally goes via something like this:

    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")

But that is indeed executed at the bottom of FindTriSYCL.cmake, so that should work.

I'll investigate this further, but I'd like to invite you to think along why this is going wrong and what to do about it.

**Comment by keryell** [comment]
The tests are using `boost::filesystem` when compiling in logging mode.
There might be a dependency issue in the CMake configuration then...
Otherwise, I think that nobody ever tried triSYCL on Windows with MinGW-w64. :-)
Perhaps @MathiasMagnus has some ideas on the question...

**Comment by Ghostkeeper** [comment]
If it's just the tests, then we'd need a different solution than the one in #202. We'd need to implement it in the `tests/CMakeLists.txt` file.

But I think that's not the case. The problem is that Boost::compute is being compiled with its offline cache:

https://github.com/triSYCL/triSYCL/blob/9eed90745f24edfc0033bf345202d7a736f092bd/cmake/FindTriSYCL.cmake#L224

According to the [getting started](https://boostorg.github.io/compute/boost_compute/getting_started.html) page of Boost::compute, this then requires linking with Boost::filesystem.

**Comment by MathiasMagnus** [comment]
I reviewed your PRs. I'm generally not fond of tempering with `CMAKE_CXX_FLAGS` and related global variables if not absolutely necessary. Changing Warning level for MSVC without emitting a warning of W3 being overriden by W4 requires tempering with it. Other than that, `FindOpenMP.cmake` documents how to use it.

**Comment by keryell** [comment]
I think this is solved by the 2 merged PR.
