### ISSUE TITLE
Fix read-only status of a buffer

### ISSUE THREAD

**Issue by keryell** [triSYCL/triSYCL#25]
As mentioned in https://github.com/triSYCL/triSYCL/pull/11 by @MathiasMagnus there is a issue on how the read-only status is computed.
Actually `tests/buffer/read_write_buffer.cpp` does not check the results. :-(
Furthermore this read-only status seems to have changed in the specification in the meantime.
So the implementation has to be fixed and cleaned up..

**Comment by keryell** [comment]
@MathiasMagnus does this solve your issue you mentioned in https://github.com/triSYCL/triSYCL/pull/11 with `tests/buffer/buffer_set_final_data_1.cpp` ?
Unfortunately the `const_cast<T *>` in the implementation is an easy way to go for now...

**Comment by MathiasMagnus** [comment]
It does indeed. It just took a few hours for me to clean up the mess in my fork. Is it safe to get rid of mate and mate2 branches?

**Comment by keryell** [comment]
Great that it fixed you issue.
Yes you can get rid of the branches.
Thanks.
