### ISSUE TITLE
Redefinition of SYCL as a diferent kind of symbol

### ISSUE THREAD

**Issue by Ruyk** [triSYCL/triSYCL#256]
The line below:

https://github.com/triSYCL/triSYCL/blob/dc50058eb5d83b8cdddd6a43c994f76ea04a8b0e/include/SYCL/sycl.hpp#L14 

Causes the following error while testing SYCL Parallel STL:

```
/SyclParallelSTL/include/sycl/helpers/sycl_namegen.hpp:38:11: error: redefinition of 'sycl' as different kind of symbol
namespace sycl {
          ^
/tmp/triSYCL-master/include/CL/sycl.hpp:15:13: note: previous definition is here
  namespace sycl = ::trisycl;
            ^
```

(See https://travis-ci.org/KhronosGroup/SyclParallelSTL/jobs/589056514) 

I am thinking this is actually a Parallel STL bug, we should not be using the sycl namespace, but I wonder if this is an expected error or you have never considered redefinition of the sycl namespace?

**Comment by keryell** [comment]
Good suggestion, even if I think that https://github.com/KhronosGroup/SyclParallelSTL/blob/master/include/sycl/helpers/sycl_namegen.hpp should not use randomly `::cl::sycl` like that.
Perhaps it is a good opportunity to think about using new namespaces?
Also I can see the parallel STL is using `::sycl`, which might be an issue in the future...
Perhaps `::sycl::ext::pstl` or `::sycl::vendor::khronos::pstl` or whatever?

I think I have fixed the namespace declarations in triSYCL to be more robust.
I was thinking to have the opportunity to use `namespace inline` for the first time, but not that time yet. :-)

**Comment by keryell** [comment]
Interestingly, if I use the ::cl namespace in a PR or commit referencing an issue, it closes the issue!
Great to have found that OpenCL with C++ can solve all the GitHub issues! The universal cure... ;-)
