### ISSUE TITLE
Some confusions about the nd_range

### ISSUE THREAD

**Issue by Chenzejun-Dummkopf** [triSYCL/triSYCL#282]
I find some examples about the SYCL‘s class nd_range.
I am confused about some APIs like 'get_global_range' , 'get_local_range', 'get_group_range' and 'get_offset'.
How to understand the global range, local range and group range?
Does the global range mean the range of the work group?
Does the local range mean the range of the work item?
What does the group range mean?

`cl::sycl::nd_range<3> three_dim_nd_range({32, 64, 128}, {16, 32, 64} );

assert(three_dim_nd_range.get_global_range() == cl::sycl::range<3>(32, 64, 128));

assert(three_dim_nd_range.get_local_range() == cl::sycl::range<3>(16, 32, 64));

assert(three_dim_nd_range.get_group_range() == cl::sycl::range<3>(2, 2, 2));

assert(three_dim_nd_range.get_offset() == cl::sycl::id<3>(0, 0, 0));
`

**Comment by j-stephan** [comment]
The global range is the set of all work-items launched for your kernel. In your example, your global range has three dimensions, with 32 work-items in the X dimension, 64 work-items in the Y dimension and 128 work-items in the Z dimension. In total your global range has 32 * 64 * 128 = 262,144 work-items.

The local range is the set of all work-items in a work-group. In your example each work-group has 16 * 32 * 64 = 32,768 work-items.

The group range is the set of all work-**groups** in the global range. You could obtain this value by dividing the global range by the local range, or you can simply call `get_group_range()`. In your example each work-group has 16 work-items in the X dimension, while the global range has 32 work items. 32/16 = 2, hence 2 in the group range. In total you have 8 work-groups. And 262,144 / 32,768 happens to be 8 as well.

The offset is an optional parameter. By default, the first work-item in your global range will have the index (0, 0, 0), the next one in the X direction (1, 0, 0), and so on. If you provide an offset of (42, 42, 42), the first work-item will have a global id of (42, 42, 42), the next one in X direction (43, 42, 42), and so on.

**Comment by Chenzejun-Dummkopf** [comment]
Thank you so much for your meaningful answers.
Now i have another questions about the DPCPP, which is mainly based on the SYCL.
Here is a DPCPP code:
`
#include “common_code.hpp”
using namespace cl::sycl;
int main(){
  int *a, *d_a;
  queue q;
  auto ctx = q.get_context();
  constexpr int N = 100;
  a = static_cast<int *>(malloc(sizeof(int)*N));
  d_a = static_cast<int *>(malloc_device(sizeof(int)*N, q.get_device(), ctx));
  for(int i = 0; i < N; i++)
     a[i] = i;
  **auto e1 = q.memcpy(d_a, a, sizeof(int)*N);**
  auto e2 = q.submit([&](**handler &h**) {
  **h.depends_on(e1);**
  h.parallel_for(range<1>(N), [=](id<1> i){
    d_a[i]++;
});
});
  q.submit([&](**handler &h**){
  **h.depends_on({e1,e2});**
  **h.memcpy(a, d_a, sizeof(int)*N);**
}).wait();
  for(int i = 0; i < N; i++)
    std::cout<<a[i]<<"\n";
  free(a);
  free(d_a,ctx);
  return 0; 
}`
I find that the class handler has no API called 'depengs_on()' from the SYCL 1.2 spec.
Class queue has no API called 'memcpy' from the SYCL 1.2 spec.
**Does the DPCPP use some extention?**
**Another question, how to compile the DPCPP code?**
I use **clang++ -fsycl** to compile the SYCL code.

**Comment by keryell** [comment]
Today SYCL 2020 Provisional has been published. \o/
https://www.khronos.org/sycl/
Perhaps it contains more explanations and bug fixes to answer some of your questions...
triSYCL does not support SYCL 2020 yet, beyond the namespaces and little details.
DPC++ seems to have a quite better support.

**Comment by Chenzejun-Dummkopf** [comment]
Thank you for your meaningful help!
