### ISSUE TITLE
Fix multiple_compilation_units test

### ISSUE THREAD

**Issue by keryell** [triSYCL/triSYCL#30]
The old test `multiple_compilation_units/parallel_for` is not deterministic.
Máté was bitten in https://github.com/triSYCL/triSYCL/pull/29.
This test has to be rewritten.

**Comment by keryell** [comment]
I think I fixed it in https://github.com/triSYCL/triSYCL/commit/715f065bdfc46455f54eb7d2ea475121a47b859f

@a-doumoulakis can you verify on your side it works?

**Comment by a-doumoulakis** [comment]
With multiple builds in different configurations succeeding and [travis-ci](https://travis-ci.org/a-doumoulakis/triSYCL/branches, "builds") not complaining we can safely say it is fixed.
