### ISSUE TITLE
Implement context to optimize OpenCL transfers

### ISSUE THREAD

**Issue by a-doumoulakis** [triSYCL/triSYCL#32]
The current implementation of context is pretty minimal. 
### OpenCL interoperability 
There is a problem with the buffer accessor that holds the ` boost::optional<boost::compute::buffer> cl_buf`, every time a new allocator is created (eg. when passing arguments to the kernel) a transfer to the device is triggered even if we could have reused a previous `boost::compute::buffer`

 A solution would be a caching mechanism inside of the buffer that associates a `cl::sycl::context` to a `boost::compute::buffer` in an unordered_map. 
Implementing `cl::sycl::context` as a `detail::shared_ptr_implementation` would allow it to be hashed and be used inside a unordered_map.

### Context implementation
A basic implementation of context could be similar to device or queue with a `context/detail/host_context` for the host, `context/detail/opencl_context` to hold the `boost::compute::context` and a `context/detail/context` that holds the virutal functions.

**Comment by keryell** [comment]
This has been solved by https://github.com/triSYCL/triSYCL/issues/33
