### ISSUE TITLE
Example of something that is not simply per-element operations?

### ISSUE THREAD

**Issue by hughperkins** [triSYCL/triSYCL#53]
Hi Ronan,

Question: are there any examples of something that is not just a simple per-element operation?  I'm thinking of eg:
- matrix multiplication?
- convolution?
- reduction?

I lookedi n examples, and found per-element addition, multiplication etc, but couldnt seem to find anything that wasnt simply per-element?

**Comment by hughperkins** [comment]
(ah, possibly `local_accessor_hierarchical_convolution.cpp`?)

**Comment by keryell** [comment]
There is also tests/jacobi.

Otherwise there are the SYCL ParallelSTL and TensorFlow projects, outside of this repository...
